---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
  options:
    config-file: .ansible-lint
platforms:
  - name: ubuntu-xenial
    profiles: ['default', 'lxd', 'vagrant']
    architecture: "x86_64"
    source:
      type: image
      mode: pull
      server: "images.linuxcontainers.org"
      protocol: "lxd"
      alias: "ubuntu/xenial"
  - name: ubuntu-disco
    profiles: ['default']
    #    architecture: "x86_64"
    source:
      type: image
      mode: pull
      server: "https://images.linuxcontainers.org"
      protocol: "lxd"
      alias: "ubuntu/disco"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
